### ISSUE TITLE
Utilize Epic's cloud save feature with games that support it

### ISSUE THREAD

**Issue by sharzy720** [ebenbruyns/junkstore#45] opened 2024-06-04 03:25 UTC
Having cloud saves supported is the main feature keeping me from switching from the heroic launcher. Ideally, it would check the cloud saves when you launch a game and update the saves when you close the game. For a better idea of how it would work look at how Heroic handles Epic's cloud saves when you set it up correctly. However, If handling the saves automatically can't be done then maybe adding a button within the plugin to manually update the saves.

**Comment by ebenbruyns** [comment] 2024-06-04 03:30
The issue isn't replicating what heroic has, the issue is that there's a pile of hidden edge cases that will blow up spectacularly for some users. I notice that you're a CS grad, you can quite easily add this yourself to the scripts with a bit of digging and a big of head scratching. This way you'll also know exactly where the limitations are and you can work around them safely on your own.

The problem with Cloud saves at the moment is the Solve for N+1 case. Getting something that kinda works is easy though.

I'm sure you have the skill set to easily add this yourself and be reasonably happy with it.

**Comment by mrsjunkrunner** [comment] 2024-06-04 04:25
duplicate of #31

**Closed** 2024-06-20 03:29 UTC
Labels: duplicate, enhancement
